apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-jwt-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  JWT_EXPIRATION: "{{ .Values.jwt.expiration }}"
